from abc import ABC, abstractmethod


class ImagePrompt:
    """
    A structured prompt object for image generation containing prompt instructions
    and target section type annotations.
    """
    def __init__(self, prompt_text: str, section_type: str = ""):
        self.prompt_text = prompt_text
        self.section_type = section_type

    def __str__(self) -> str:
        return self.prompt_text


class ImageResponse:
    """
    A structured response object returned by image generation providers containing
    raw generated bytes and model credentials records.
    """
    def __init__(self, image_bytes: bytes, provider: str, model: str = ""):
        self.image_bytes = image_bytes
        self.provider = provider
        self.model = model


class ImageProvider(ABC):
    @abstractmethod
    def generate_image(self, prompt: ImagePrompt, model: str = None) -> ImageResponse:
        """
        Sends the generation instructions to the model API. Returns a structured ImageResponse.
        """
        pass
